# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import miner_pb2 as miner__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in miner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MinerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentChallenge = channel.unary_unary(
                '/miner.Miner/GetCurrentChallenge',
                request_serializer=miner__pb2.Empty.SerializeToString,
                response_deserializer=miner__pb2.ChallengeInfo.FromString,
                _registered_method=True)
        self.SubmitSolution = channel.unary_unary(
                '/miner.Miner/SubmitSolution',
                request_serializer=miner__pb2.SolutionSubmission.SerializeToString,
                response_deserializer=miner__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.Add = channel.unary_unary(
                '/miner.Miner/Add',
                request_serializer=miner__pb2.AdderRequest.SerializeToString,
                response_deserializer=miner__pb2.AdderResponse.FromString,
                _registered_method=True)


class MinerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCurrentChallenge(self, request, context):
        """Pega o desafio atual (TransactionID e Challenge)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSolution(self, request, context):
        """Submete uma solução candidata para o Transaction corrente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """(Opcional) Para reutilizar exemplo anterior: um serviço Adder simples
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentChallenge,
                    request_deserializer=miner__pb2.Empty.FromString,
                    response_serializer=miner__pb2.ChallengeInfo.SerializeToString,
            ),
            'SubmitSolution': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSolution,
                    request_deserializer=miner__pb2.SolutionSubmission.FromString,
                    response_serializer=miner__pb2.SubmitResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=miner__pb2.AdderRequest.FromString,
                    response_serializer=miner__pb2.AdderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'miner.Miner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('miner.Miner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Miner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCurrentChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miner.Miner/GetCurrentChallenge',
            miner__pb2.Empty.SerializeToString,
            miner__pb2.ChallengeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miner.Miner/SubmitSolution',
            miner__pb2.SolutionSubmission.SerializeToString,
            miner__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/miner.Miner/Add',
            miner__pb2.AdderRequest.SerializeToString,
            miner__pb2.AdderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
