# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: miner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'miner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bminer.proto\x12\x05miner\"\x07\n\x05\x45mpty\"M\n\rChallengeInfo\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x11\n\tchallenge\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"R\n\x12SolutionSubmission\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x11\n\tcandidate\x18\x03 \x01(\t\"_\n\x0eSubmitResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10winner_client_id\x18\x03 \x01(\x05\x12\x10\n\x08solution\x18\x04 \x01(\t\"$\n\x0c\x41\x64\x64\x65rRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1c\n\rAdderResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\xbe\x01\n\x05Miner\x12;\n\x13GetCurrentChallenge\x12\x0c.miner.Empty\x1a\x14.miner.ChallengeInfo\"\x00\x12\x44\n\x0eSubmitSolution\x12\x19.miner.SolutionSubmission\x1a\x15.miner.SubmitResponse\"\x00\x12\x32\n\x03\x41\x64\x64\x12\x13.miner.AdderRequest\x1a\x14.miner.AdderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_CHALLENGEINFO']._serialized_start=31
  _globals['_CHALLENGEINFO']._serialized_end=108
  _globals['_SOLUTIONSUBMISSION']._serialized_start=110
  _globals['_SOLUTIONSUBMISSION']._serialized_end=192
  _globals['_SUBMITRESPONSE']._serialized_start=194
  _globals['_SUBMITRESPONSE']._serialized_end=289
  _globals['_ADDERREQUEST']._serialized_start=291
  _globals['_ADDERREQUEST']._serialized_end=327
  _globals['_ADDERRESPONSE']._serialized_start=329
  _globals['_ADDERRESPONSE']._serialized_end=357
  _globals['_MINER']._serialized_start=360
  _globals['_MINER']._serialized_end=550
# @@protoc_insertion_point(module_scope)
